# Generated by Django 6.0.6 on 2026-06-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_type', models.CharField(choices=[('Above Ground', 'Above Ground'), ('In-ground', 'In-ground'), ('Portable', 'Portable')], max_length=50)),
                ('approximate_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('water_level', models.CharField(choices=[('Below Skimmer', 'Below Skimmer'), ('At Normal', 'At Normal'), ('Above Skimmer', 'Above Skimmer')], max_length=50)),
                ('construction_type', models.CharField(choices=[('Liner', 'Liner'), ('Tile', 'Tile'), ('Pebblecrete', 'Pebblecrete'), ('Concrete', 'Concrete'), ('Fibreglass', 'Fibreglass')], max_length=50)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=50)),
                ('approximate_age', models.CharField(choices=[('1-5 Years', '1-5 Years'), ('5-10 Years', '5-10 Years'), ('10+ Years', '10+ Years')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/pool_information/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool_information', to='inspections.inspection')),
            ],
        ),
    ]
