# Generated by Django 6.0.6 on 2026-06-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_poolinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMainDrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_lines_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('main_drain_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('main_drain_visible', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('suction_issue', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/return_main_drain/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_main_drain', to='inspections.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='WaterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chlorine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stabiliser', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alkalinity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salt', models.CharField(blank=True, max_length=50, null=True)),
                ('water_clarity', models.CharField(blank=True, choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Green', 'Green')], max_length=20, null=True)),
                ('needs_balancing', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('needs_emptying', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('algae_present', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('scum_line', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('scale_forming', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('tiles_missing', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('approximate_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/water_analysis/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_analysis', to='inspections.inspection')),
            ],
        ),
    ]
