# Generated by Django 6.0.6 on 2026-06-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_returnmaindrain_wateranalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coping_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('tiles_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('surface_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('cracks_visible', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('leaks_visible', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('staining_visible', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/pool_features/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool_features', to='inspections.inspection')),
            ],
        ),
    ]
