# Generated by Django 6.0.6 on 2026-06-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_poolfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkimmerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skimmer_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('skimmer_lid_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('basket_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('suction_working', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/skimmer_box/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skimmer_box', to='inspections.inspection')),
            ],
        ),
    ]
