# Generated by Django 6.0.6 on 2026-06-30 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_skimmerbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lights_installed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('lights_working', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('light_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('transformer_condition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('N/A', 'N/A')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/lights/')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='light_inspection', to='inspections.inspection')),
            ],
        ),
    ]
